### PR TITLE
fix(typegen): use "strict" type notation for all generated types

### PR DESCRIPTION
**Pull request by futurewasfree**
Let our models always represent types after validation and coercion.
This fixes static analysis errors (pyright) and issue #55. 

chore(version): bump MINOR

### CODE REVIEW

**Comment by caniko** [comment]
Can you apply the strictness to the strict submodule only?

**Comment by futurewasfree** [comment]
Maybe I don't understand something.. strict type notation is already there for strict types.

If we do not apply it to all types - then we don't have a fix for issue reported (#55). I was under impression that this is something we've agreed earlier.

What is your concern about having it for all types?

**Comment by caniko** [comment]
Oh my goodness, you are right. I should've checked before including you. I am sorry for the missunderstanding, and my lack of dilligence.

I believe that we should keep things as they are, strict is strict. Not strict lacks the static type-safety. I will write a couple words for this in the `README.md`.

Let's go back to the issue to keep discussing before we close the PR. I really want to understand why this is useful.

**Comment by futurewasfree** [comment]
We've also had this conversation almost a year ago:
https://github.com/caniko/pydantic-numpy/discussions/33

This is where we have slightly different opinions, personally I never pass `FilePath` or `MultiArrayNumpyFile` in our codebase.
Wondering if these could be left to a helper instead?  then we would get quite straightforward type hints for models and static analysis working. Validation still allows "non-strictness" in such case.

Documentation improvements are always nice, but also what I could observe: people at first just jump on "non-strict" types and start using them without reading much docs. They might need additional guidance to discover "stricter" versions.

**Comment by caniko** [comment]
Yes, I remember everything now.

This is very good feedback, and it makes sense. How about we make them both submodules, and make strict the default namespace?

**Comment by futurewasfree** [comment]
Yes, this solution sounds like a good alternative. 
What does making strict one the default means in reality? Importing it on top level `pydantic_numpy/__init__.py` ?

Re: confusion part. I think #52 is another recent occurrence of it. So good if we change it ;)

**Comment by caniko** [comment]
OK, I believe we are in consensus! 🥳 

I will close the PR. Thanks again

**Comment by futurewasfree** [comment]
Yes, this sounds good. Thanks, Can!

**Pull request closed without merging**
